const data = {
  products: [
    {
      name: 'nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      Image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'nike slim shirts',
      slug: 'nike-slim-shirts',
      category: 'Shirts',
      Image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'nike slim pants',
      slug: 'nike-slim-pants',
      category: 'Shirts',
      Image: '/images/p3.jpg',
      price: 220,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Shirts',
      Image: '/images/p4.jpg',
      price: 320,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
  ],
};

export default data;
